### ISSUE TITLE
project purpose?

### ISSUE THREAD

**Issue by foxpcteam** [TheLogosProject/LogosProject#1]
HI,
what is the project about?

**Comment by matthewguenther** [comment]
Good morning,
Here is a brief description of the project. I'm going to update the readme immediately after sending this reply.

"The Logos Academy is a Full Stack (MEAN) web application that on-boards new CrossFit gym members through an expert-tested curriculum. It focuses on safe and effective development of functional movements and provides personalized, attainable goals for each of their members that are easily accessible on the mobile friendly app. The app also deepens and further develops the close-knit box community by allowing fellow gym members to share and track their progress as well as encourage each other to achieve their goals.

Key Technologies: HTML5, CSS3, JavaScript, jQuery, MongoDB, Mongoose, Node.js, Express, AngularJS, MaterializeCSS, Passport, Bower, Grunt, Yeoman, Git, Github"

**Comment by matthewguenther** [comment]
The readme has been updated now. :)
